services:
  your-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nfc2t-img
    container_name: nfc2t-cont
    volumes:
      - ./:/app
    ports:
      - '5173:5173'
    # working_dir: /app
   # command: npm run dev -- --host 0.0.0.0