[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.6"
candid_derive = "0.6.6"
ic-cdk = "0.13.1"
ic-cdk-macros = "0.9.0"
serde = "1.0.197"
